RidePal\RoutesBundle\Entity\Routes:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        routeName:
            type: string
            length: '8'
        totalStops:
            type: integer
        firstStop:
            type: integer
        lastStop:
            type: integer
    lifecycleCallbacks: {  }
